[tool.ruff]
line-length = 150
exclude = [
    ".venv",
    "__pycache__",
    "examples",
]

[tool.ruff.lint]
select = ["E", "I"]

[tool.ruff.format]
line-ending = "lf"
quote-style = "double"
indent-style = "space"